<?php
// Do not edit this file directly, instead copy it into your
// application directorie's config folder and the changes you make
// will cascade over what you see here.
// TODO LOL... cascading not yet implemented so yeah edit this directly
// at least for now.
return array(
  "storage" => array(
    "strategy" => "GUID",
    "driver" => "FileSystem",
    "basepath" => $app['path'] . '/public',
  ),
  "filers" => array(
    "location" => $app['path'].'/filers',
    ),
  #"FilerName" => array(
  #  "VersionName" => array(
  #    "path" => "/some/dir"
  #    )
  #  )
  );
